# Generated by Django 4.0.4 on 2022-05-24 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_remove_question_pub_date_question_question_writer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
