# Generated by Django 4.0.4 on 2022-05-27 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_alter_member_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='member',
            table='member_member',
        ),
    ]
