# Generated by Django 4.0.4 on 2022-05-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResult',
            fields=[
                ('surveyResult_idx', models.AutoField(db_column='surveyResult_idx', primary_key=True, serialize=False)),
                ('member_idx', models.IntegerField()),
                ('surveyResult_date', models.DateTimeField(db_column='surveyResult_date')),
                ('surveyResult_recommendation', models.CharField(db_column='surveyResult_recommendation', max_length=100)),
                ('surveyResult_answers', models.CharField(db_column='surveyResult_answers', max_length=100)),
                ('surveyResult_rarea', models.CharField(blank=True, db_column='surveyResult_rarea', max_length=100, null=True)),
            ],
        ),
    ]
