# Generated by Django 4.0.4 on 2022-05-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bbs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(verbose_name=100)),
                ('title', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=255)),
                ('writer', models.CharField(max_length=255)),
            ],
        ),
    ]
