# Generated by Django 4.0.4 on 2022-05-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbs',
            name='content',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='bbs',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='bbs',
            name='writer',
            field=models.CharField(max_length=500),
        ),
    ]
