# Generated by Django 4.0.4 on 2022-05-26 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surveyResult_idx', models.IntegerField()),
                ('member_idx', models.IntegerField()),
                ('surveyResult_date', models.DateTimeField()),
                ('surveyResult_answers', models.CharField(max_length=100)),
                ('surveyResult_recommendation', models.CharField(max_length=100)),
                ('surveyResult_rarea', models.CharField(max_length=100)),
            ],
        ),
    ]
