# Generated by Django 4.0.4 on 2022-05-27 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveyResult', '0002_alter_surveyresult_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='surveyresult',
            table='surveyresult',
        ),
    ]
