# Generated by Django 4.0.4 on 2022-05-27 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveyResult', '0004_alter_surveyresult_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='surveyresult',
            table='surveyResult',
        ),
    ]
