# Generated by Django 4.0.4 on 2022-05-26 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_idx', models.IntegerField()),
                ('survey_question', models.CharField(max_length=100)),
                ('survey_choices', models.CharField(max_length=100)),
            ],
        ),
    ]
