# Generated by Django 4.0.4 on 2022-05-27 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_alter_survey_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='survey',
            table='survey',
        ),
    ]
