# Generated by Django 4.0.4 on 2022-05-27 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_alter_survey_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='survey',
            table='survey_survey',
        ),
    ]
